* Makefile
Running This file will setup a new system.
#+BEGIN_SRC makefile-gmake :noweb yes :tangle Makefile
default: install-yay install-packages link-config enable-services

install-yay:
  <<install-yay>>

install-packages:
  yay -S `cat packages.txt`

link-config:
  stow --restow .

enable-services:
	<<systemd-commands()>>
#+END_SRC
** Install =yay=
#+BEGIN_SRC makefile-gmake :noweb-ref install-yay
sudo pacman -Sy git
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
rm -rf yay
#+END_SRC
** Enable Services
Setup all our =systemd= services.
#+NAME: systemd-services
- mpd.service
- checkmail.timer
- syncthing.service
- automount.service
- inkscapefigures.service
- inkscapewatch.service
We a quick script to turn these services into the appropriate =systemd=
commands. It's a little hacky, but I write some Python to output valid bash code.
#+NAME: systemd-commands
#+BEGIN_SRC python :results output silent :var services=systemd-services
out = r"""for service in {}; do
    for action in "enable" "start"; do
        systemctl --user $action $service
    done
done""".format(" ".join(["'{}'".format(x[0]) for x in services]))
print(out)
#+END_SRC
* Suspend
Lock the screen on suspend.
#+BEGIN_SRC systemd :tangle /sudo::/etc/systemd/system/suspend@gautam.service
[Unit]
Description=User suspend actions
Before=sleep.target

[Service]
User=%I
Type=simple
Environment=DISPLAY=:0
ExecStart=/usr/bin/slock
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sleep.target
#+END_SRC
Dock to the appropriate state (external monitor or just laptop monitor) after resuming.
#+BEGIN_SRC systemd :tangle /sudo::/etc/systemd/system/resume@gautam.service
[Unit]
Description=User suspend actions
After=sleep.target

[Service]
User=%I
Type=simple
ExecStart=/home/%I/bin/dock

[Install]
WantedBy=sleep.target
#+END_SRC
* Watch for HDMI monitor
This [[http://jasonwryan.com/blog/2014/01/20/udev/][blog post]] was integral in getting this working.
#+BEGIN_SRC conf :tangle /sudo::/etc/udev/rules.d/98-monitor-hotplug.rules
ACTION=="change", KERNEL=="card0", SUBSYSTEM=="drm", ENV{DISPLAY}=":0", ENV{XAUTHORITY}="/home/gautam/.Xauthority", RUN+="/bin/bash /home/gautam/bin/dock"
#+END_SRC
Reload the =udev= rules.
#+BEGIN_SRC sh :results silent :dir /sudo::
udevadm control --reload-rules
#+END_SRC
*  Mount USB drives to =/media=
The default is =/run/media/$user=.
#+BEGIN_SRC conf :tangle /sudo::/etc/udev/rules.d/99-udisks2.rules
ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{UDISKS_FILESYSTEM_SHARED}="1"
#+END_SRC
Clean stale mountpoints on boot.
#+BEGIN_SRC conf :tangle /sudo::/etc/tmpfiles.d/media.conf
D /media 0755 root root 0 -
#+END_SRC
* Options
# Local variables:
# after-save-hook: org-babel-tangle
# end:

#  LocalWords:  inkscapefigures inkscapewatch syncthing automount
