#+PROPERTY: header-args :tangle config
* Startup
The first thing I do is set up my screens. This is a script in my =~/bin= that
checks if I have an external monitor plugged in and uses =xrandr= accordingly.
#+BEGIN_SRC conf
exec --no-startup-id dock
#+END_SRC
Then I start up Emacs and the browser.
#+BEGIN_SRC conf
exec emacs
exec qutebrowser
#+END_SRC
Then I make the screen emit a bearable amount of blue light.
#+BEGIN_SRC conf
exec --no-startup-id redshift
#+END_SRC
Speaking of bearable, the default key repeat delay and speed is too low for me.
The first term is the delay, the second term is the speed. For the record,
=exec_always= runs the command even when i3 is reloaded (as opposed to started for
the first time).
#+BEGIN_SRC conf
exec_always --no-startup-id xset r rate 125 60
#+END_SRC
This makes Caps Lock act as a Control key.
#+BEGIN_SRC conf
exec_always --no-startup-id setxkbmap -option ctrl:nocaps
#+END_SRC
I also want moving my hand down to scroll the screen up. My trackpad is a little
messed up, so tap-to-click is very useful.
#+BEGIN_SRC conf
exec_always --no-startup-id xinput set-prop "DLL0704:01 06CB:76AE Touchpad" "libinput Natural Scrolling Enabled" 1
exec_always --no-startup-id xinput set-prop "DLL0704:01 06CB:76AE Touchpad" "libinput Tapping Enabled" 1
#+END_SRC
* Basic Controls
This corresponds to the Super/Windows key on my keyboard.
#+BEGIN_SRC conf
set $mod Mod4
#+END_SRC
Using the mouse with this modifier drags floating windows.
#+BEGIN_SRC conf
floating_modifier $mod
#+END_SRC
I couldn't get Hack to work right with this.
#+BEGIN_SRC conf
font pango:monospace 8
#+END_SRC
This removes borders and titlebars entirely. At first, I thought this would be
disorienting, but I've honestly gotten used to it.
#+BEGIN_SRC conf
default_border none
hide_edge_borders both
#+END_SRC
I start apps with =rofi=.
#+BEGIN_SRC conf
bindsym $mod+d exec rofi -show combi
bindsym $mod+b exec rofi -show window
#+END_SRC
Default basic bindings.
#+BEGIN_SRC conf
# kill focused window
bindsym $mod+q kill
# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child
#+END_SRC
* Graphics
** Displays
Sometimes I need to manually dock or undock.
#+BEGIN_SRC conf
set $mode_monitors Monitor setup: (0) laptop only, (1) external
mode "$mode_monitors" {
  bindsym 0 exec --no-startup-id "xrandr --output DP1 --off", mode "default"
  bindsym 1 exec --no-startup-id "/home/gautam/bin/dock", mode "default"

  # back to normal: Enter or Escape
  bindsym Return mode "default"
  bindsym Escape mode "default"
}

bindsym $mod+p exec --no-startup-id dock
bindsym $mod+shift+p mode "$mode_monitors"
#+END_SRC
Adjusting brightness.
#+BEGIN_SRC conf
bindsym XF86MonBrightnessDown exec --no-startup-id change-brightness -U 5
bindsym XF86MonBrightnessUp exec --no-startup-id change-brightness -A 5
#+END_SRC
** Workspaces
A simple script + Org Babel tangling lets us save a lot of repetition over the
default config.
#+BEGIN_SRC conf :noweb yes
<<workspace-bindings()>>
#+END_SRC
The one thing to be careful about is that we don't try to bind =$mod+10=, because
there is no "10" key.
#+NAME: workspace-bindings
#+BEGIN_SRC sh :tangle no :results output :eval yes
for num in $(seq 1 10); do
    if [ $num == 10 ]; then
        bind=0
    else
        bind=$num
    fi
    echo "set \$ws$num \"$num\""
    echo "bindsym \$mod+$bind workspace \$ws$num"
    echo "bindsym \$mod+Shift+$bind move container to workspace \$ws$num"
done
#+END_SRC
Assign workspaces to certain displays.
#+BEGIN_SRC conf
workspace $ws1 output primary
#+END_SRC
#+BEGIN_SRC conf :noweb yes
<<workspace-assignments()>>
#+END_SRC
#+NAME: workspace-assignments
#+BEGIN_SRC sh :tangle no :results output :eval yes
for num in $(seq 2 6); do
    echo "workspace \$ws$num output DP-1 DP1 primary"
done
#+END_SRC
Assign windows to certain workspaces.
#+BEGIN_SRC conf
assign [class="^qutebrowser$"] → $ws2
assign [class="^mpv$"] → output DP1
assign [class="^Inkscape$"] → $ws6
#+END_SRC
Assign certain properties to windows.
#+BEGIN_SRC conf
for_window [class="^Emacs$" title="^floatingEmacs$"] floating enable
for_window [class="^Emacs$" title="^org-capture-pop-frame$"] enable focus
assign [class="^Emacs$" title="^org-capture-pop-frame$"] → output DP-1 DP1
#+END_SRC
I really like having a window open on one monitor and using the keyboard to
control stuff on another monitor.
#+BEGIN_SRC conf
focus_follows_mouse no
#+END_SRC
This is a cool script that lets me swap the workspaces on my monitors.
#+BEGIN_SRC conf
bindsym $mod+shift+s exec --no-startup-id $HOME/.i3/i3-display-swap.sh
#+END_SRC
** Window Management
All default stuff.
#+BEGIN_SRC conf
# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right
#+END_SRC
Resize windows.
#+BEGIN_SRC conf
# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"
#+END_SRC
* Utilities
** Audio
The script =music-control= is in my =bin=. If it can, it connects to =emms= in Emacs.
It falls back on =mpc=. This way, the numbers for the duration elapsed of a song
is correct in Emacs.
#+BEGIN_SRC conf
bindsym XF86AudioMute exec --no-startup-id "change-volume toggle"
bindsym XF86AudioLowerVolume exec --no-startup-id "change-volume 3dB- unmute"
bindsym XF86AudioRaiseVolume exec --no-startup-id "change-volume 3dB+ unmute"

bindsym XF86AudioPrev exec --no-startup-id music-control prev
bindsym XF86AudioNext exec --no-startup-id music-control next
bindsym XF86AudioPlay exec --no-startup-id music-control toggle
bindsym Pause exec --no-startup-id music-control toggle
#+END_SRC
** Screenshots
Again, we use Babel to save some repetition.
#+BEGIN_SRC conf :noweb yes
<<screenshot-commands()>>
#+END_SRC
The Python variable =commands= stores the binding and the options to =scrot=, the
program we will use for taking the screenshot.
#+BEGIN_SRC conf :tangle no
bindsym --release BIND exec --no-startup-id "scrot OPTIONS"
#+END_SRC
The values =path= and =target= are defined in the Org source block.
#+NAME: screenshot-commands
#+BEGIN_SRC python :eval yes :tangle no :results output :var path="'/home/gautam/pictures/screenshots/%F_%T_$wx$h.png'" target="'xclip -selection clipboard -target image/png -i $f'"
commands = {
    "Print": "-s {} -e {}".format(path,target),
    "Shift-Print": "{} -e {}".format(path,target),
    "Ctrl-Print": "{}".format(path)}

for bind in commands:
    print("bindsym --release {} exec --no-startup-id \"scrot {}\"".format(bind,commands[bind]))
#+END_SRC
** Terminal
#+BEGIN_SRC conf
bindsym $mod+Return exec --no-startup-id emacsclient -e "(let ((current-prefix-arg '(4))) (call-interactively 'eshell-other-frame))"
bindsym $mod+Shift+Return exec i3-sensible-terminal
#+END_SRC
** Shutdown Menu
#+BEGIN_SRC conf
set $mode_system System (l) lock, (e) logout, (s) suspend, (h) hibernate, (r) reboot, (Shift+s) shutdown
mode "$mode_system" {
    bindsym l exec --no-startup-id slock, mode "default"
    bindsym e exec --no-startup-id i3-msg exit, mode "default"
    bindsym s exec --no-startup-id systemctl suspend, mode "default"
    bindsym h exec --no-startup-id systemctl hibernate, mode "default"
    bindsym r exec --no-startup-id systemctl reboot, mode "default"
    bindsym Shift+s exec --no-startup-id systemctl poweroff -i, mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+Pause mode "$mode_system"
bindsym $mod+Delete mode "$mode_system"
#+END_SRC
** Reloading i3
#+BEGIN_SRC conf
# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
#+END_SRC
* =i3bar=
The official i3 status bar.
#+BEGIN_SRC conf
bar {
    status_command i3status --config=~/.i3/.i3status.conf
}
#+END_SRC
* Options
# Local variables:
# after-save-hook: org-babel-tangle
# end:
